export const mockProducts = [
  {
    id: "1",
    name: "Fresh Organic Apples",
    price: 4.99,
    stock: 15,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/2966150/pexels-photo-2966150.jpeg",
    ],
    description: "Fresh organic apples from local farmsss",
    category: "processed",
    tags: ["organic", "fresh", "local"],
  },
  {
    id: "2",
    name: "Whole Wheat Bread",
    price: 2.49,
    stock: 30,
    available: true,
    measurement_unit: "loaf",
    image_urls: [
      "https://images.pexels.com/photos/6824475/pexels-photo-6824475.jpeg",
    ],
    description: "Freshly baked whole wheat bread with no preservatives",
    category: "fresh",
    tags: ["whole wheat", "fresh", "healthy"],
  },
  {
    id: "3",
    name: "Free-range Eggs",
    price: 3.99,
    stock: 50,
    available: true,
    measurement_unit: "dozen",
    image_urls: [
      "https://images.pexels.com/photos/4911785/pexels-photo-4911785.jpeg",
    ],
    description: "Farm fresh free-range eggs",
    category: "fresh",
    tags: ["free-range", "protein", "organic"],
  },
  {
    id: "4",
    name: "Almond Milk",
    price: 5.25,
    stock: 20,
    available: true,
    measurement_unit: "litre",
    image_urls: [
      "https://images.pexels.com/photos/3658482/pexels-photo-3658482.jpeg",
    ],
    description: "Unsweetened almond milk, lactose-free and vegan",
    category: "inputs",
    tags: ["vegan", "dairy-free", "healthy"],
  },
  {
    id: "5",
    name: "Tomatoes",
    price: 2.99,
    stock: 25,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/673673/pexels-photo-673673.jpeg",
    ],
    description: "Juicy red tomatoes perfect for cooking and salads",
    category: "fresh",
    tags: ["fresh", "local", "seasonal"],
  },
];

export const mockFavorites = [
  {
    id: "4",
    name: "Almond Milk",
    price: 5.25,
    stock: 20,
    available: true,
    measurement_unit: "litre",
    image_urls: [
      "https://images.pexels.com/photos/3658482/pexels-photo-3658482.jpeg",
    ],
    description: "Unsweetened almond milk, lactose-free and vegan",
    category: "inputs",
    tags: ["vegan", "dairy-free", "healthy"],
  },
  {
    id: "5",
    name: "Tomatoes",
    price: 2.99,
    stock: 25,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/673673/pexels-photo-673673.jpeg",
    ],
    description: "Juicy red tomatoes perfect for cooking and salads",
    category: "fresh",
    tags: ["fresh", "local", "seasonal"],
  },
];
