export const mockProducts = [
  {
    id: "1",
    name: "Organic Heirloom Tomatoes",
    description:
      "Fresh, vine-ripened heirloom tomatoes grown with organic practices. Perfect for salads, cooking, or eating fresh.",
    category: "Vegetables",
    price: 6.99,
    unit: "per lb",
    quantity: 150,
    images: [
      "https://images.pexels.com/photos/673673/pexels-photo-673673.jpeg",
    ],
    farmerId: "1",
    farmerName: "Green Valley Farm",
    farmerLocation: "California, USA",
    isOrganic: true,
    pickupAvailable: true,
    deliveryAvailable: true,
    harvestedDate: "2024-01-15",
    rating: 4.8,
    reviewCount: 32,
    createdAt: "2024-01-10",
    updatedAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Fresh Spinach Leaves",
    description:
      "Crisp, nutritious spinach leaves perfect for salads, smoothies, or cooking.",
    category: "Leafy Greens",
    price: 4.5,
    unit: "per bunch",
    quantity: 80,
    images: [
      "https://images.pexels.com/photos/6824475/pexels-photo-6824475.jpeg",
    ],
    farmerId: "1",
    farmerName: "Green Valley Farm",
    farmerLocation: "California, USA",
    isOrganic: true,
    pickupAvailable: true,
    deliveryAvailable: true,
    harvestedDate: "2024-01-20",
    rating: 4.6,
    reviewCount: 18,
    createdAt: "2024-01-18",
    updatedAt: "2024-01-20",
  },
  {
    id: "3",
    name: "Farm Fresh Eggs",
    description:
      "Free-range chicken eggs from happy hens. Rich, golden yolks and superior taste.",
    category: "Dairy & Eggs",
    price: 5.99,
    unit: "per dozen",
    quantity: 120,
    images: [
      "https://images.pexels.com/photos/4911785/pexels-photo-4911785.jpeg",
    ],
    farmerId: "1",
    farmerName: "Happy Hen Farm",
    farmerLocation: "Vermont, USA",
    isOrganic: false,
    pickupAvailable: true,
    deliveryAvailable: true,
    harvestedDate: "2024-01-21",
    rating: 4.7,
    reviewCount: 28,
    createdAt: "2024-01-19",
    updatedAt: "2024-01-21",
  },
  {
    id: "4",
    name: "Sweet Corn",
    description:
      "Sweet, tender corn on the cob. Perfect for grilling or boiling. Non-GMO and pesticide-free.",
    category: "Vegetables",
    price: 0.75,
    unit: "per ear",
    quantity: 200,
    images: [
      "https://images.pexels.com/photos/3658482/pexels-photo-3658482.jpeg",
    ],
    farmerId: "1",
    farmerName: "Sunny Acres Farm",
    farmerLocation: "Iowa, USA",
    isOrganic: false,
    pickupAvailable: true,
    deliveryAvailable: true,
    harvestedDate: "2024-01-18",
    rating: 4.9,
    reviewCount: 45,
    createdAt: "2024-01-16",
    updatedAt: "2024-01-18",
  },
];
