// src/mockData/product.ts
import { Product } from "@/types/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Fresh Organic Apples",
    price: 4.99,
    stock: 15,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/2966150/pexels-photo-2966150.jpeg",
    ],
    description: "Fresh organic apples from local farmsss",
    category: "processed",
    tags: ["organic", "fresh", "local"],
    project_id: "proj101",
  },
  {
    id: "2",
    name: "Whole Wheat Bread",
    price: 2.49,
    stock: 30,
    available: true,
    measurement_unit: "loaf",
    image_urls: [
      "https://images.pexels.com/photos/6824475/pexels-photo-6824475.jpeg",
    ],
    description: "Freshly baked whole wheat bread with no preservatives",
    category: "fresh",
    tags: ["whole wheat", "fresh", "healthy"],
    project_id: "334234",
  },
  {
    id: "3",
    name: "Free-range Eggs",
    price: 3.99,
    stock: 50,
    available: true,
    measurement_unit: "dozen",
    image_urls: [
      "https://images.pexels.com/photos/4911785/pexels-photo-4911785.jpeg",
    ],
    description: "Farm fresh free-range eggs",
    category: "fresh",
    tags: ["free-range", "protein", "organic"],
    project_id: "j",
  },
  {
    id: "4",
    name: "Almond Milk",
    price: 5.25,
    stock: 20,
    available: true,
    measurement_unit: "litre",
    image_urls: [
      "https://images.pexels.com/photos/3658482/pexels-photo-3658482.jpeg",
    ],
    description: "Unsweetened almond milk, lactose-free and vegan",
    category: "inputs",
    tags: ["vegan", "dairy-free", "healthy"],
    project_id: "1",
  },
  {
    id: "5",
    name: "Tomatoes",
    price: 2.99,
    stock: 25,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/673673/pexels-photo-673673.jpeg",
    ],
    description: "Juicy red tomatoes perfect for cooking and salads",
    category: "fresh",
    tags: ["fresh", "local", "seasonal"],
    project_id: "p",
  },
  {
    id: "6",
    name: "Fresh Organic Apples",
    price: 4.99,
    stock: 15,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/2966150/pexels-photo-2966150.jpeg",
    ],
    description: "Fresh organic apples from local farmsss",
    category: "processed",
    tags: ["organic", "fresh", "local"],
    project_id: "proj101",
  },
  {
    id: "7",
    name: "Whole Wheat Bread",
    price: 2.49,
    stock: 30,
    available: true,
    measurement_unit: "loaf",
    image_urls: [
      "https://images.pexels.com/photos/6824475/pexels-photo-6824475.jpeg",
    ],
    description: "Freshly baked whole wheat bread with no preservatives",
    category: "fresh",
    tags: ["whole wheat", "fresh", "healthy"],
    project_id: "334234",
  },
  {
    id: "8",
    name: "Free-range Eggs",
    price: 3.99,
    stock: 50,
    available: true,
    measurement_unit: "dozen",
    image_urls: [
      "https://images.pexels.com/photos/4911785/pexels-photo-4911785.jpeg",
    ],
    description: "Farm fresh free-range eggs",
    category: "fresh",
    tags: ["free-range", "protein", "organic"],
    project_id: "j",
  },
  {
    id: "9",
    name: "Almond Milk",
    price: 5.25,
    stock: 20,
    available: true,
    measurement_unit: "litre",
    image_urls: [
      "https://images.pexels.com/photos/3658482/pexels-photo-3658482.jpeg",
    ],
    description: "Unsweetened almond milk, lactose-free and vegan",
    category: "inputs",
    tags: ["vegan", "dairy-free", "healthy"],
    project_id: "1",
  },
  {
    id: "10",
    name: "Tomatoes",
    price: 2.99,
    stock: 25,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/673673/pexels-photo-673673.jpeg",
    ],
    description: "Juicy red tomatoes perfect for cooking and salads",
    category: "fresh",
    tags: ["fresh", "local", "seasonal"],
    project_id: "p",
  },
  {
    id: "11",
    name: "Fresh Organic Apples",
    price: 4.99,
    stock: 15,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/2966150/pexels-photo-2966150.jpeg",
    ],
    description: "Fresh organic apples from local farmsss",
    category: "processed",
    tags: ["organic", "fresh", "local"],
    project_id: "proj101",
  },
  {
    id: "12",
    name: "Whole Wheat Bread",
    price: 2.49,
    stock: 30,
    available: true,
    measurement_unit: "loaf",
    image_urls: [
      "https://images.pexels.com/photos/6824475/pexels-photo-6824475.jpeg",
    ],
    description: "Freshly baked whole wheat bread with no preservatives",
    category: "fresh",
    tags: ["whole wheat", "fresh", "healthy"],
    project_id: "334234",
  },
  {
    id: "13",
    name: "Free-range Eggs",
    price: 3.99,
    stock: 50,
    available: true,
    measurement_unit: "dozen",
    image_urls: [
      "https://images.pexels.com/photos/4911785/pexels-photo-4911785.jpeg",
    ],
    description: "Farm fresh free-range eggs",
    category: "fresh",
    tags: ["free-range", "protein", "organic"],
    project_id: "j",
  },
  {
    id: "14",
    name: "Almond Milk",
    price: 5.25,
    stock: 20,
    available: true,
    measurement_unit: "litre",
    image_urls: [
      "https://images.pexels.com/photos/3658482/pexels-photo-3658482.jpeg",
    ],
    description: "Unsweetened almond milk, lactose-free and vegan",
    category: "inputs",
    tags: ["vegan", "dairy-free", "healthy"],
    project_id: "1",
  },
  {
    id: "15",
    name: "Tomatoes",
    price: 2.99,
    stock: 25,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/673673/pexels-photo-673673.jpeg",
    ],
    description: "Juicy red tomatoes perfect for cooking and salads",
    category: "fresh",
    tags: ["fresh", "local", "seasonal"],
    project_id: "p",
  },
  {
    id: "16",
    name: "Fresh Organic Apples",
    price: 4.99,
    stock: 15,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/2966150/pexels-photo-2966150.jpeg",
    ],
    description: "Fresh organic apples from local farmsss",
    category: "processed",
    tags: ["organic", "fresh", "local"],
    project_id: "proj101",
  },
  {
    id: "17",
    name: "Whole Wheat Bread",
    price: 2.49,
    stock: 30,
    available: true,
    measurement_unit: "loaf",
    image_urls: [
      "https://images.pexels.com/photos/6824475/pexels-photo-6824475.jpeg",
    ],
    description: "Freshly baked whole wheat bread with no preservatives",
    category: "fresh",
    tags: ["whole wheat", "fresh", "healthy"],
    project_id: "334234",
  },
  {
    id: "18",
    name: "Free-range Eggs",
    price: 3.99,
    stock: 50,
    available: true,
    measurement_unit: "dozen",
    image_urls: [
      "https://images.pexels.com/photos/4911785/pexels-photo-4911785.jpeg",
    ],
    description: "Farm fresh free-range eggs",
    category: "fresh",
    tags: ["free-range", "protein", "organic"],
    project_id: "j",
  },
  {
    id: "19",
    name: "Almond Milk",
    price: 5.25,
    stock: 20,
    available: true,
    measurement_unit: "litre",
    image_urls: [
      "https://images.pexels.com/photos/3658482/pexels-photo-3658482.jpeg",
    ],
    description: "Unsweetened almond milk, lactose-free and vegan",
    category: "inputs",
    tags: ["vegan", "dairy-free", "healthy"],
    project_id: "1",
  },
  {
    id: "20",
    name: "Tomatoes",
    price: 2.99,
    stock: 25,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/673673/pexels-photo-673673.jpeg",
    ],
    description: "Juicy red tomatoes perfect for cooking and salads",
    category: "fresh",
    tags: ["fresh", "local", "seasonal"],
    project_id: "p",
  },
  {
    id: "21",
    name: "Fresh Organic Apples",
    price: 4.99,
    stock: 15,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/2966150/pexels-photo-2966150.jpeg",
    ],
    description: "Fresh organic apples from local farmsss",
    category: "processed",
    tags: ["organic", "fresh", "local"],
    project_id: "proj101",
  },
  {
    id: "22",
    name: "Whole Wheat Bread",
    price: 2.49,
    stock: 30,
    available: true,
    measurement_unit: "loaf",
    image_urls: [
      "https://images.pexels.com/photos/6824475/pexels-photo-6824475.jpeg",
    ],
    description: "Freshly baked whole wheat bread with no preservatives",
    category: "fresh",
    tags: ["whole wheat", "fresh", "healthy"],
    project_id: "334234",
  },
  {
    id: "23",
    name: "Free-range Eggs",
    price: 3.99,
    stock: 50,
    available: true,
    measurement_unit: "dozen",
    image_urls: [
      "https://images.pexels.com/photos/4911785/pexels-photo-4911785.jpeg",
    ],
    description: "Farm fresh free-range eggs",
    category: "fresh",
    tags: ["free-range", "protein", "organic"],
    project_id: "j",
  },
  {
    id: "24",
    name: "Almond Milk",
    price: 5.25,
    stock: 20,
    available: true,
    measurement_unit: "litre",
    image_urls: [
      "https://images.pexels.com/photos/3658482/pexels-photo-3658482.jpeg",
    ],
    description: "Unsweetened almond milk, lactose-free and vegan",
    category: "inputs",
    tags: ["vegan", "dairy-free", "healthy"],
    project_id: "1",
  },
  {
    id: "25",
    name: "Tomatoes",
    price: 2.99,
    stock: 25,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/673673/pexels-photo-673673.jpeg",
    ],
    description: "Juicy red tomatoes perfect for cooking and salads",
    category: "fresh",
    tags: ["fresh", "local", "seasonal"],
    project_id: "p",
  },
  {
    id: "26",
    name: "Fresh Organic Apples",
    price: 4.99,
    stock: 15,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/2966150/pexels-photo-2966150.jpeg",
    ],
    description: "Fresh organic apples from local farmsss",
    category: "processed",
    tags: ["organic", "fresh", "local"],
    project_id: "proj101",
  },
  {
    id: "27",
    name: "Whole Wheat Bread",
    price: 2.49,
    stock: 30,
    available: true,
    measurement_unit: "loaf",
    image_urls: [
      "https://images.pexels.com/photos/6824475/pexels-photo-6824475.jpeg",
    ],
    description: "Freshly baked whole wheat bread with no preservatives",
    category: "fresh",
    tags: ["whole wheat", "fresh", "healthy"],
    project_id: "334234",
  },
  {
    id: "28",
    name: "Free-range Eggs",
    price: 3.99,
    stock: 50,
    available: true,
    measurement_unit: "dozen",
    image_urls: [
      "https://images.pexels.com/photos/4911785/pexels-photo-4911785.jpeg",
    ],
    description: "Farm fresh free-range eggs",
    category: "fresh",
    tags: ["free-range", "protein", "organic"],
    project_id: "j",
  },
  {
    id: "29",
    name: "Almond Milk",
    price: 5.25,
    stock: 20,
    available: true,
    measurement_unit: "litre",
    image_urls: [
      "https://images.pexels.com/photos/3658482/pexels-photo-3658482.jpeg",
    ],
    description: "Unsweetened almond milk, lactose-free and vegan",
    category: "inputs",
    tags: ["vegan", "dairy-free", "healthy"],
    project_id: "1",
  },
  {
    id: "30",
    name: "Tomatoes",
    price: 2.99,
    stock: 25,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/673673/pexels-photo-673673.jpeg",
    ],
    description: "Juicy red tomatoes perfect for cooking and salads",
    category: "fresh",
    tags: ["fresh", "local", "seasonal"],
    project_id: "p",
  },
  {
    id: "31",
    name: "Fresh Organic Apples",
    price: 4.99,
    stock: 15,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/2966150/pexels-photo-2966150.jpeg",
    ],
    description: "Fresh organic apples from local farmsss",
    category: "processed",
    tags: ["organic", "fresh", "local"],
    project_id: "proj101",
  },
  {
    id: "32",
    name: "Whole Wheat Bread",
    price: 2.49,
    stock: 30,
    available: true,
    measurement_unit: "loaf",
    image_urls: [
      "https://images.pexels.com/photos/6824475/pexels-photo-6824475.jpeg",
    ],
    description: "Freshly baked whole wheat bread with no preservatives",
    category: "fresh",
    tags: ["whole wheat", "fresh", "healthy"],
    project_id: "334234",
  },
  {
    id: "33",
    name: "Free-range Eggs",
    price: 3.99,
    stock: 50,
    available: true,
    measurement_unit: "dozen",
    image_urls: [
      "https://images.pexels.com/photos/4911785/pexels-photo-4911785.jpeg",
    ],
    description: "Farm fresh free-range eggs",
    category: "fresh",
    tags: ["free-range", "protein", "organic"],
    project_id: "j",
  },
  {
    id: "34",
    name: "Almond Milk",
    price: 5.25,
    stock: 20,
    available: true,
    measurement_unit: "litre",
    image_urls: [
      "https://images.pexels.com/photos/3658482/pexels-photo-3658482.jpeg",
    ],
    description: "Unsweetened almond milk, lactose-free and vegan",
    category: "inputs",
    tags: ["vegan", "dairy-free", "healthy"],
    project_id: "1",
  },
  {
    id: "35",
    name: "Tomatoes",
    price: 2.99,
    stock: 25,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/673673/pexels-photo-673673.jpeg",
    ],
    description: "Juicy red tomatoes perfect for cooking and salads",
    category: "fresh",
    tags: ["fresh", "local", "seasonal"],
    project_id: "p",
  },
  {
    id: "36",
    name: "Fresh Organic Apples",
    price: 4.99,
    stock: 15,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/2966150/pexels-photo-2966150.jpeg",
    ],
    description: "Fresh organic apples from local farmsss",
    category: "processed",
    tags: ["organic", "fresh", "local"],
    project_id: "proj101",
  },
  {
    id: "37",
    name: "Whole Wheat Bread",
    price: 2.49,
    stock: 30,
    available: true,
    measurement_unit: "loaf",
    image_urls: [
      "https://images.pexels.com/photos/6824475/pexels-photo-6824475.jpeg",
    ],
    description: "Freshly baked whole wheat bread with no preservatives",
    category: "fresh",
    tags: ["whole wheat", "fresh", "healthy"],
    project_id: "334234",
  },
  {
    id: "38",
    name: "Free-range Eggs",
    price: 3.99,
    stock: 50,
    available: true,
    measurement_unit: "dozen",
    image_urls: [
      "https://images.pexels.com/photos/4911785/pexels-photo-4911785.jpeg",
    ],
    description: "Farm fresh free-range eggs",
    category: "fresh",
    tags: ["free-range", "protein", "organic"],
    project_id: "j",
  },
  {
    id: "39",
    name: "Almond Milk",
    price: 5.25,
    stock: 20,
    available: true,
    measurement_unit: "litre",
    image_urls: [
      "https://images.pexels.com/photos/3658482/pexels-photo-3658482.jpeg",
    ],
    description: "Unsweetened almond milk, lactose-free and vegan",
    category: "inputs",
    tags: ["vegan", "dairy-free", "healthy"],
    project_id: "1",
  },
  {
    id: "40",
    name: "Tomatoes",
    price: 2.99,
    stock: 25,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/673673/pexels-photo-673673.jpeg",
    ],
    description: "Juicy red tomatoes perfect for cooking and salads",
    category: "fresh",
    tags: ["fresh", "local", "seasonal"],
    project_id: "p",
  },
];

export const mockFavorites = [
  {
    id: "4",
    name: "Almond Milk",
    price: 5.25,
    stock: 20,
    available: true,
    measurement_unit: "litre",
    image_urls: [
      "https://images.pexels.com/photos/3658482/pexels-photo-3658482.jpeg",
    ],
    description: "Unsweetened almond milk, lactose-free and vegan",
    category: "inputs",
    tags: ["vegan", "dairy-free", "healthy"],
  },
  {
    id: "5",
    name: "Tomatoes",
    price: 2.99,
    stock: 25,
    available: true,
    measurement_unit: "kg",
    image_urls: [
      "https://images.pexels.com/photos/673673/pexels-photo-673673.jpeg",
    ],
    description: "Juicy red tomatoes perfect for cooking and salads",
    category: "fresh",
    tags: ["fresh", "local", "seasonal"],
  },
];
